apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rocket-vs
  namespace: {{ .Values.app.rocketchat.namespace }}
spec:
  hosts:
  - {{ .Values.app.rocketchat.server.host }}
  gateways:
  - rocket-gateway
  http:
  - route:
    - destination:
        host: rocketchat-svc
        port:
          number: 3000
