apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rocket-gateway
  namespace: {{ .Values.app.rocketchat.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.app.rocketchat.server.host }}
