apiVersion: v1
kind: Service
metadata:
  labels:
    app: rocketchat-server
  name: rocketchat-svc
  namespace: {{ .Values.rocketchat.namespace }}
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: rocketchat-server
