apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-server
  namespace: {{ .Values.rocketchat.namespace }}
spec:
  replicas: {{ .Values.rocketchat.server.replicaCount }}
  selector:
    matchLabels:
      app: rocketchat-server
  template:
    metadata:
      labels:
        app: rocketchat-server
    spec:
      containers:
        - name: rocketchat-server
          image: rocketchat/rocket.chat:latest
          ports:
            - containerPort: 3000
          envFrom:
          - secretRef:
              name: chat-db-secret
          imagePullPolicy: Always